# Generated by Django 5.2.5 on 2025-09-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=10)),
                ('student_phone_number', models.CharField(max_length=10)),
                ('student_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('student_password', models.CharField(max_length=45)),
                ('mun_experience', models.CharField(max_length=10)),
                ('committee_preference_1', models.CharField(choices=[('United Nations General Assembly- Social, Humanitarian and Cultural Committee (Third Committee)', 'United Nations General Assembly- Social, Humanitarian and Cultural Committee (Third Committee)'), ('Assembly of the African Union', 'Assembly of the African Union'), ('International Seabed Authority (Legal and Technical Commission)', 'International Seabed Authority (Legal and Technical Commission)'), ("United Nations High-Level Advisory Body on Artificial Intelligence (Office of the Secretary-General's Envoy on Technology)", "United Nations High-Level Advisory Body on Artificial Intelligence (Office of the Secretary-General's Envoy on Technology)"), ('United Nations Security Council', 'United Nations Security Council'), ('Meeting of Harvard Corporation and the Board of Overseers', 'Meeting of Harvard Corporation and the Board of Overseers'), ('Executive Review Meeting of the Directorate-General of Civil Aviation. (Ministry of Civil Aviation, Government of India)', 'Executive Review Meeting of the Directorate-General of Civil Aviation. (Ministry of Civil Aviation, Government of India)'), ('People’s Court of Athens, 399 BCE', 'People’s Court of Athens, 399 BCE'), ('National Emergency Coordination Council', 'National Emergency Coordination Council'), ('The Sovereignty Expropriation Directorate', 'The Sovereignty Expropriation Directorate'), ('Executive Command of the Nasrid Emirate', 'Executive Command of the Nasrid Emirate'), ('International Press - Journalism', 'International Press - Journalism'), ('International Press - Photography', 'International Press - Photography'), ('Ad-Hoc Committee of the Secretary-General', 'Ad-Hoc Committee of the Secretary-General')], max_length=500)),
                ('committee_preference_2', models.CharField(choices=[('United Nations General Assembly- Social, Humanitarian and Cultural Committee (Third Committee)', 'United Nations General Assembly- Social, Humanitarian and Cultural Committee (Third Committee)'), ('Assembly of the African Union', 'Assembly of the African Union'), ('International Seabed Authority (Legal and Technical Commission)', 'International Seabed Authority (Legal and Technical Commission)'), ("United Nations High-Level Advisory Body on Artificial Intelligence (Office of the Secretary-General's Envoy on Technology)", "United Nations High-Level Advisory Body on Artificial Intelligence (Office of the Secretary-General's Envoy on Technology)"), ('United Nations Security Council', 'United Nations Security Council'), ('Meeting of Harvard Corporation and the Board of Overseers', 'Meeting of Harvard Corporation and the Board of Overseers'), ('Executive Review Meeting of the Directorate-General of Civil Aviation. (Ministry of Civil Aviation, Government of India)', 'Executive Review Meeting of the Directorate-General of Civil Aviation. (Ministry of Civil Aviation, Government of India)'), ('People’s Court of Athens, 399 BCE', 'People’s Court of Athens, 399 BCE'), ('National Emergency Coordination Council', 'National Emergency Coordination Council'), ('The Sovereignty Expropriation Directorate', 'The Sovereignty Expropriation Directorate'), ('Executive Command of the Nasrid Emirate', 'Executive Command of the Nasrid Emirate'), ('International Press - Journalism', 'International Press - Journalism'), ('International Press - Photography', 'International Press - Photography'), ('Ad-Hoc Committee of the Secretary-General', 'Ad-Hoc Committee of the Secretary-General')], max_length=500)),
                ('is_head_delegate', models.BooleanField(default=False)),
                ('incharge_name', models.CharField(max_length=100)),
                ('incharge_phone_number', models.CharField(max_length=10)),
                ('incharge_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
