# Generated by Django 5.2.5 on 2025-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_class', models.CharField(max_length=10)),
                ('school_designation', models.CharField(max_length=100)),
                ('school_phone_number', models.CharField(max_length=10)),
                ('school_email', models.CharField(max_length=100)),
                ('school_password', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='incharge_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
