# Generated by Django 5.2.5 on 2025-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_school_alter_student_incharge_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='alloted_committee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='alloted_portfolio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_school_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
